version: '2'
services:
 namenode:
      build: ./hdfs/
      image: hdfs_cdh:5.13
      command: hdfs namenode
      environment:
        - HADOOP_NAMENODE_OPTS=-Xms200m -Xmx200m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:+PrintTenuringDistribution
      ports:
          - "50071:50070"
          - "9000:9000"
      hostname: hdfs-namenode
      mem_limit: 400m
      volumes:
        - "./data/namenode:/data"

 datanode:
      build: ./hdfs/
      image: hdfs_cdh:5.13
      command: hdfs datanode
      environment:
        - HADOOP_DATANODE_OPTS=-Xms200m -Xmx200m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:+PrintTenuringDistribution
      ports:
          - "50075:50075"
      links:
          - namenode:hdfs-namenode
      depends_on:
          - namenode
      mem_limit: 400m
      volumes:
        - "./data/datanode/:/data"

networks:
  default:
    external:
      name: wasp-docker
